import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import type { AddressInfo } from "node:net";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { loadConfig } from "../src/config.js";
import { startHttpServer, type RunningHttpServer } from "../src/http-server.js";
import { createServices } from "../src/mcp-server.js";

describe("task dashboard", () => {
  let running: RunningHttpServer | undefined;
  let dir: string | undefined;
  afterEach(async () => { await running?.close(); running = undefined; if (dir) await rm(dir, { recursive: true, force: true }); });

  it("protects and serves task timeline APIs", async () => {
    dir = await mkdtemp(path.join(os.tmpdir(), "cokacremote-dashboard-"));
    const token = "dashboard-test-secret-0123456789abcdef";
    const policyFile = path.join(dir, "safety-policy.json");
    await writeFile(policyFile, JSON.stringify({ version: 1, defaults: { outsideWorkspace: "approval-required" } }));
    const config = loadConfig({ MCP_AUTH_TOKEN: token, MCP_HOST: "127.0.0.1", MCP_DEFAULT_CWD: dir, MCP_SAFETY_MODE: "safe", MCP_SAFETY_POLICY_FILE: policyFile }, dir);
    config.port = 0;
    const services = createServices(config);
    const task = await services.taskJournal.startTask("Dashboard test", dir);
    await services.taskJournal.record("tool.started", { taskId: task.taskId, toolName: "exec_command" });
    await services.taskJournal.record("tool.completed", { taskId: task.taskId, toolName: "exec_command", durationMs: 12.3 });
    running = await startHttpServer(config, services);
    const address = running.httpServer.address() as AddressInfo;
    const base = `http://127.0.0.1:${address.port}/dashboard`;
    expect((await fetch(base)).status).toBe(401);
    const headers = { authorization: `Bearer ${token}` };
    const html = await fetch(base, { headers });
    expect(html.status).toBe(200);
    const dashboardHtml = await html.text();
    expect(dashboardHtml).toContain("Development task timeline");
    const script = dashboardHtml.match(/<script>([\s\S]*?)<\/script>/)?.[1];
    expect(script).toBeTruthy();
    expect(() => new Function(script!)).not.toThrow();
    const tasks = await (await fetch(`${base}/api/tasks`, { headers })).json() as { tasks: Array<{ taskId: string }> };
    expect(tasks.tasks.some((item) => item.taskId === task.taskId)).toBe(true);
    const events = await (await fetch(`${base}/api/tasks/${task.taskId}/events`, { headers })).json() as { events: Array<{ event: string }> };
    expect(events.events.map((event) => event.event)).toEqual(["task.started", "tool.started", "tool.completed"]);
    const pending = services.safetyPolicy.request("exec_command", "sudo systemctl restart nginx", "sudo systemctl restart nginx");
    const approvals = await (await fetch(`${base}/api/approvals`, { headers })).json() as { approvals: Array<{ approvalId: string }> };
    expect(approvals.approvals.some((item) => item.approvalId === pending.approvalId)).toBe(true);
    const approved = await fetch(`${base}/api/approvals/${pending.approvalId}/approve`, { method: "POST", headers });
    expect(approved.status).toBe(200);
    expect(services.safetyPolicy.list().find((item) => item.approvalId === pending.approvalId)?.approvedAt).toBeTruthy();
    const deniedPending = services.safetyPolicy.request("exec_command", "sudo echo denied", "sudo echo denied");
    const denied = await fetch(`${base}/api/approvals/${deniedPending.approvalId}/deny`, { method: "POST", headers });
    expect(denied.status).toBe(200);
    expect(services.safetyPolicy.list().some((item) => item.approvalId === deniedPending.approvalId)).toBe(false);
    const stalePending = services.safetyPolicy.request("exec_command", "sudo echo stale", "sudo echo stale");
    services.safetyPolicy.approve(stalePending.approvalId);
    const policyResponse = await (await fetch(`${base}/api/policy`, { headers })).json() as { editable: boolean; policy: { version: number } };
    expect(policyResponse.editable).toBe(true);
    expect(policyResponse.policy.version).toBe(1);
    const invalid = await fetch(`${base}/api/policy/validate`, { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ version: 2 }) });
    expect(invalid.status).toBe(400);
    const updatedPolicy = { version: 1, commands: [{ id: "deny-danger", pattern: "danger", decision: "deny" }] };
    const saved = await fetch(`${base}/api/policy`, { method: "PUT", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify(updatedPolicy) });
    expect(saved.status).toBe(200);
    expect(services.safetyPolicy.list()).toEqual([]);
    expect(() => services.safetyPolicy.consume(stalePending.approvalId, "exec_command", "sudo echo stale")).toThrow("Unknown or expired approval");
    expect(services.safetyPolicy.assessCommand("danger").decision).toBe("deny");
    expect(JSON.parse(await readFile(policyFile, "utf8"))).toMatchObject(updatedPolicy);
    await writeFile(policyFile, JSON.stringify({ version: 1, commands: [{ id: "allow-danger", pattern: "danger", decision: "allow" }] }));
    const reloaded = await fetch(`${base}/api/policy/reload`, { method: "POST", headers });
    expect(reloaded.status).toBe(200);
    expect(services.safetyPolicy.assessCommand("danger").decision).toBe("allow");
    const historyResponse = await (await fetch(`${base}/api/policy/history`, { headers })).json() as { history: Array<{ revisionId: string; action: string; sha256: string; entryHash?: string }>; verification: { integrity: boolean; chainedEntries: number } };
    expect(historyResponse.history.map((entry) => entry.action)).toEqual(["reload", "save"]);
    expect(historyResponse.history.every((entry) => entry.sha256.length === 64 && entry.entryHash?.length === 64)).toBe(true);
    expect(historyResponse.verification).toMatchObject({ integrity: true, chainedEntries: 2 });
    const saveRevision = historyResponse.history.find((entry) => entry.action === "save");
    expect(saveRevision).toBeTruthy();
    const diffResponse = await (await fetch(`${base}/api/policy/diff/${saveRevision!.revisionId}`, { headers })).json() as { diff: Array<{ type: string; line: string }> };
    expect(diffResponse.diff.some((line) => line.type === "remove" && line.line.includes("deny-danger"))).toBe(true);
    expect(diffResponse.diff.some((line) => line.type === "add" && line.line.includes("allow-danger"))).toBe(true);
    const rollback = await fetch(`${base}/api/policy/rollback/${saveRevision!.revisionId}`, { method: "POST", headers });
    expect(rollback.status).toBe(200);
    expect(services.safetyPolicy.assessCommand("danger").decision).toBe("deny");
    const afterRollback = await (await fetch(`${base}/api/policy/history`, { headers })).json() as { history: Array<{ action: string; rollbackFromRevisionId?: string }> };
    expect(afterRollback.history[0]!.action).toBe("rollback");
    expect(afterRollback.history[0]!.rollbackFromRevisionId).toBe(saveRevision!.revisionId);
    const missingRollback = await fetch(`${base}/api/policy/rollback/not-a-revision`, { method: "POST", headers });
    expect(missingRollback.status).toBe(404);
  });
});
